global:
  # Как часто собирать метрики (каждые 15 секунд)
  scrape_interval: 15s

scrape_configs:
  - job_name: 'productionsystem'
    static_configs:
      # Адрес нашего API откуда брать метрики
      - targets: ['api:8080']